[package]
name = "throwaway-check-doi"
version = "0.1.0"
authors = ["Martin Czygan <martin.czygan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1"
lazy_static = "1.0"
failure = "*"
